### PR TITLE
Updated DocumentDb client package ref

### PR DESCRIPTION
**Pull request by 13daysaweek**
Updated the DocumentDb client package to use the Microsoft.Azure.DocumentDB rather than the deprecated Microsoft.Azure.Documents.Client package.

(this is my first pull request, so please let me know if I messed anything up!)

### CODE REVIEW

**Comment by robdmoore** [comment]
I assume you checked it to make sure it still works against a document db instance?

@nblumhardt is the change to assembly version and the Serilog version OK?

**Comment by 13daysaweek** [comment]
@robdmoore I did successfully test against my document db instance.

**Comment by johnkattenhorn** [comment]
Any chance of getting the merged and a new nuget package ?

**Comment by nblumhardt** [comment]
Hi all - the peculiar version numbers that were in `CommonAssemblyInfo.cs` are used by the build process (a bit hacky, I know) so it will be necessary to revert that change here. +1 on the PR from me :-)

**Comment by 13daysaweek** [comment]
Hi - sorry for the mixup on CommonAssemblyInfo.cs, not sure how that happened.  Anyway, I've reverted the change so I think we should be good to go.

**Comment by nblumhardt** [comment]
Thanks @13daysaweek :-)

**Pull request merged**
