### PR TITLE
Add log processing on dedicated worker thread

### PR DESCRIPTION
**Pull request by saleem-mirza**
Sink constructor accepts optional parameter to initiate buffering and concurrent log processing.
Added feature to send log to azure using dedicated background thread. 
Added some cleanup code to flush remaining messages in parallel when disposing off sink.

### CODE REVIEW

**Comment by sirpadington** [comment]
Awesome job man. We were looking at pulling this into one of our netcore projects!

**Comment by nblumhardt** [comment]
Hi @saleem-mirza - thanks for the PR! We've just released [`Serilog.Sinks.Async`](https://github.com/serilog/serilog-sinks-async) which allows you to do this by writing:

```csharp
    .WriteTo.Async(a => a.AzureDocumentDB(...))
```

Can you let me know if `WriteTo.Async()` covers this case for you?

Regards,
Nick

**Comment by saleem-mirza** [comment]
@nblumhardt Though this is a great feature and you are heading in right direction but unfortunately, in my test `.WriteTo.Async` didn't worked.

I have attached a demo gist as test. New feature failed to log any message and application exits even before Sink gets chance to send any message to DocumentDB.

Please see https://gist.github.com/saleem-mirza/2cbb5eef479e3912acb791cd932adea8

**Comment by nblumhardt** [comment]
Ah, I see. Nice job!

Ideally, we'd use `PeriodicBatchingSink` here and a bulk-insert API to push data into DocumentDB - even in the parallel case, 55 events/second is pretty limited, and on a single-core machine it's going to be back up to the 8.7 events/second observed with `Async()`.

In the short-term though, improving performance by any means possible sounds like a good move, and I think we should take this change on board.

I don't think we should expose a public `ConcurrentLogEventSink` class from this assembly though. In future we might ship something like a _Serilog.Sinks.Parallel_ for this (for example), but for now making it an internal implementation detail seems more fitting with the purpose of this package. Is it possible to close this up, by moving the members back down into `AzureDocumentDBSink` or otherwise finding a way to make the type private?

Cheers,
Nick

**Comment by saleem-mirza** [comment]
Thanks Nick,

As I mention, performance numbers are highly subjective and environment dependent. It can go up or otherwise. The reason I coded `ConcurrentLogEventSink` is to eliminate complexity and also to reuse feature easily with any other sink.

But to make change local, I'll revert my last commit and it will be pretty much a monolithic solution.
I do like and support future development of `Serilog.Sinks.Parallel`. Logs are very important so motive is to offload or mitigate performance penalties but without loosing any log even in event of application crash.

**Comment by nblumhardt** [comment]
Looking great, thanks @saleem-mirza.

The workflow in this repo goes PR -> dev -> master, I've re-targeted to the dev branch so that we can get a `-dev-nnnnn` package out. Will set up a PR to release onto master once we've had confirmation that the dev release is good :+1:

**Comment by nblumhardt** [comment]
Ah, I see this repository doesn't do dev publishing yet; straight to master we go! (An update to the new build scripts and layout from serilog/serilog is sorely needed).

**Pull request merged**
