### PR TITLE
Add 'HttpMessageHandler' to extension method.

### PR DESCRIPTION
**Pull request by etsms**
- Support ability to add a custom httpHandler to DocumentClient (to allow proxy and other http related configurations)

### CODE REVIEW

**Comment by saleem-mirza** [comment]
Thank you for raising PR. Please explain what issue this PR is resolving or what value it's adding to sink.

**Comment by etsms** [comment]
Our sites sit behind a proxy. I need to configure document DB proxy configuration. That’s done by providing a custom HttpHandler.

**Comment by saleem-mirza** [comment]
In my opinion, proxy should be handled at application level not at library level. Libraries have very specific responsibilities. 

Please consider configuring application configuration files.

**Comment by etsms** [comment]
@saleem-mirza how does one go about configuring the HttpMessageHandler via DocumentDB through this library?

DocumentDB exposes properties to change message handlers. Proxy stuff is only part of large capability set that HttpMessageHandlers offer you.

That said - if I wanted to modify the DocumentClient instance within this library to support our requirements, how would I?

**Pull request closed without merging**
